name: 'Bug Report'
description: Create a ticket for a bug
title: '[BUG]: '
labels: ['bug']
projects: ['AgentScript-AI/3']
assignees:
    - kedrzu
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: textarea
      id: what-happened
      attributes:
          label: What happened?
          description: Also tell us, what did you expect to happen?
          placeholder: Tell us what you see!
          value: 'A bug happened!'
      validations:
          required: true
